version: 1.0
Resources: 
  -TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition:
      LoadBalancerInfo:
        ContainerName: "audit-auth-mayu-container"
        ContainerPort: "8000"
      PlatformVersion: "Latest"
